name: appsyncmasterclass
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: eu-west-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool

# tells serverless-appsync-plugin where the appsync templates are
mappingTemplatesLocation: mapping-templates
mappingTemplates:
  - type: Query
    field: getMyProfile
    dataSource: usersTable
    request: Query.getMyProfile.request.vtl
    response: Query.getMyProfile.response.vtl
  - type: Query
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFunction
    request: false
    response: false
  - type: Query
    field: getTweets
    dataSource: tweetsTable
    request: Query.getTweets.request.vtl
    response: Query.getTweets.response.vtl
  - type: Query
    field: getMyTimeline
    dataSource: timelinesTable
    request: Query.getMyTimeline.request.vtl
    response: Query.getMyTimeline.response.vtl
  - type: Query
    field: getLikes
    dataSource: likesTable
    request: Query.getLikes.request.vtl
    response: Query.getLikes.response.vtl

  - type: Mutation
    field: editMyProfile
    dataSource: usersTable
    request: Mutation.editMyProfile.request.vtl
    response: Mutation.editMyProfile.response.vtl
  - type: Mutation
    field: tweet
    dataSource: tweetFunction
    request: false
    response: false
  - type: Mutation
    field: like
    dataSource: likesMutation
    request: Mutation.like.request.vtl
    response: Mutation.like.response.vtl
  - type: Mutation
    field: unlike
    dataSource: unlikeMutation
    request: Mutation.unlike.request.vtl
    response: Mutation.unlike.response.vtl
  - type: Mutation
    field: retweet
    dataSource: retweetFunction
    request: false
    response: false
  - type: Mutation
    field: unretweet
    dataSource: unretweetFunction
    request: false
    response: false
  - type: Mutation
    field: reply
    dataSource: replyFunction
    request: false
    response: false

  # nested resolvers
  - type: Tweet
    field: profile
    dataSource: usersTable
  - type: Tweet
    field: liked
    dataSource: likesTable
  - type: Tweet
    field: retweeted
    dataSource: retweetsTable
  - type: UnhydratedTweetsPage
    field: tweets
    dataSource: tweetsTable
  - type: MyProfile
    field: tweets
    dataSource: tweetsTable
  - type: OtherProfile
    field: tweets
    dataSource: tweetsTable
    request: MyProfile.tweets.response.vtl
    response: MyProfile.tweets.request.vtl
  - type: Retweet
    field: profile
    dataSource: usersTable
    request: Tweet.profile.request.vtl
    response: Tweet.profile.response.vtl
  - type: Retweet
    field: retweetOf
    dataSource: tweetsTable
  - type: Reply
    field: profile
    dataSource: usersTable
    request: Tweet.profile.request.vtl
    response: Tweet.profile.response.vtl
  - type: Reply
    field: inReplyToTweet
    dataSource: tweetsTable
  - type: Reply
    field: inReplyToUser
    dataSource: usersTable
  - type: Reply
    field: retweeted
    dataSource: retweetsTable
    request: Tweet.retweeted.request.vtl
    response: Tweet.retweeted.response.vtl
  - type: Reply
    field: liked
    dataSource: likesTable
    request: Tweet.liked.request.vtl
    response: Tweet.liked.response.vtl

dataSources:
  - type: NONE
    name: none
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable
  - type: AMAZON_DYNAMODB
    name: tweetsTable
    config:
      tableName: !Ref TweetsTable
  - type: AMAZON_DYNAMODB
    name: timelinesTable
    config:
      tableName: !Ref TimelinesTable
  - type: AMAZON_DYNAMODB
    name: likesTable
    config:
      tableName: !Ref LikesTable
  - type: AMAZON_DYNAMODB
    name: retweetsTable
    config:
      tableName: !Ref RetweetsTable
  - type: AMAZON_DYNAMODB
    name: likesMutation
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn
  - type: AMAZON_DYNAMODB
    name: unlikeMutation
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:DeleteItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn
  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrl
  - type: AWS_LAMBDA
    name: tweetFunction
    config:
      functionName: tweetFunction
  - type: AWS_LAMBDA
    name: retweetFunction
    config:
      functionName: retweetFunction
  - type: AWS_LAMBDA
    name: unretweetFunction
    config:
      functionName: unretweetFunction
  - type: AWS_LAMBDA
    name: replyFunction
    config:
      functionName: replyFunction

substitutions:
  TweetsTable: !Ref TweetsTable
  LikesTable: !Ref LikesTable
  UsersTable: !Ref UsersTable
