name: appsyncmasterclass
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: eu-west-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool

# tells serverless-appsync-plugin where the appsync templates are
mappingTemplatesLocation: mapping-templates
mappingTemplates:
  - type: Query
    field: getMyProfile
    dataSource: usersTable
    request: Query.getMyProfile.request.vtl
    response: Query.getMyProfile.response.vtl
  - type: Query
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFunction
    request: false
    response: false
  - type: Query
    field: getTweets
    dataSource: tweetsTable
    request: Query.getTweets.request.vtl
    response: Query.getTweets.response.vtl
  - type: Query
    field: getMyTimeline
    dataSource: timelinesTable
    request: Query.getMyTimeline.request.vtl
    response: Query.getMyTimeline.response.vtl

  - type: Mutation
    field: editMyProfile
    dataSource: usersTable
    request: Mutation.editMyProfile.request.vtl
    response: Mutation.editMyProfile.response.vtl
  - type: Mutation
    field: tweet
    dataSource: tweetFunction
    request: false
    response: false
  - type: Mutation
    field: like
    dataSource: likesMutation
    request: Mutation.like.request.vtl
    response: Mutation.like.response.vtl

  # nested resolvers
  - type: Tweet
    field: profile
    dataSource: usersTable
  - type: Tweet
    field: liked
    dataSource: likesTable
  - type: TimelinePage
    field: tweets
    dataSource: tweetsTable

dataSources:
  - type: NONE
    name: none
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable
  - type: AMAZON_DYNAMODB
    name: tweetsTable
    config:
      tableName: !Ref TweetsTable
  - type: AMAZON_DYNAMODB
    name: timelinesTable
    config:
      tableName: !Ref TimelinesTable
  - type: AMAZON_DYNAMODB
    name: likesTable
    config:
      tableName: !Ref LikesTable
  - type: AMAZON_DYNAMODB
    name: likesMutation
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn
  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrl
  - type: AWS_LAMBDA
    name: tweetFunction
    config:
      functionName: tweetFunction

substitutions:
  TweetsTable: !Ref TweetsTable
  LikesTable: !Ref LikesTable
  UsersTable: !Ref UsersTable
